require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('../models/Question');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/gk-battle';

const questions = [
  // ═══════════════════════════════════════════════════════════════
  //  INDIA — Geography (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "What is the capital of India?", options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the largest state of India by area?", options: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Uttar Pradesh"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which river is known as the 'Ganga of the South'?", options: ["Krishna", "Godavari", "Kaveri", "Narmada"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "How many states are there in India?", options: ["28", "29", "27", "30"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Which is the smallest state of India by area?", options: ["Sikkim", "Goa", "Tripura", "Mizoram"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which city is known as the 'Pink City'?", options: ["Jodhpur", "Udaipur", "Jaipur", "Jaisalmer"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The Thar Desert is located in which state?", options: ["Gujarat", "Rajasthan", "Madhya Pradesh", "Haryana"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the longest river in India?", options: ["Yamuna", "Godavari", "Ganga", "Brahmaputra"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "India shares its longest international border with which country?", options: ["Pakistan", "China", "Bangladesh", "Nepal"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which state is known as 'God's Own Country'?", options: ["Goa", "Kerala", "Tamil Nadu", "Karnataka"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Mount Everest is on the border of which two countries?", options: ["India & China", "Nepal & China", "India & Nepal", "Bhutan & China"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which Indian city is called the 'City of Joy'?", options: ["Mumbai", "Chennai", "Kolkata", "Hyderabad"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Kanchenjunga is the highest peak in which country?", options: ["Nepal", "India", "Bhutan", "China"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "The Andaman and Nicobar Islands are located in which sea?", options: ["Arabian Sea", "Bay of Bengal", "Indian Ocean", "South China Sea"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which state has the longest coastline in India?", options: ["Maharashtra", "Tamil Nadu", "Gujarat", "Kerala"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the national river of India?", options: ["Yamuna", "Ganga", "Brahmaputra", "Godavari"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Dal Lake is located in which Indian city?", options: ["Shimla", "Srinagar", "Manali", "Dehradun"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which Indian state is the largest producer of tea?", options: ["Kerala", "West Bengal", "Assam", "Tamil Nadu"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Chilika Lake is located in which state?", options: ["Andhra Pradesh", "Odisha", "West Bengal", "Tamil Nadu"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which city is known as the 'Silicon Valley of India'?", options: ["Hyderabad", "Pune", "Bengaluru", "Chennai"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The Ganges originates from which place?", options: ["Kedarnath", "Gangotri", "Badrinath", "Yamunotri"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which Indian city is famous for the Charminar?", options: ["Lucknow", "Jaipur", "Hyderabad", "Agra"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Loktak Lake is located in which state?", options: ["Manipur", "Meghalaya", "Mizoram", "Nagaland"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Which is the highest dam in India?", options: ["Bhakra Dam", "Tehri Dam", "Hirakud Dam", "Sardar Sarovar Dam"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Sundarbans is located in which state?", options: ["Odisha", "West Bengal", "Assam", "Kerala"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which city is called the 'Manchester of India'?", options: ["Surat", "Ahmedabad", "Mumbai", "Kanpur"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which state is known as the 'Land of Five Rivers'?", options: ["Haryana", "Rajasthan", "Punjab", "Himachal Pradesh"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Jog Falls is located in which state?", options: ["Kerala", "Karnataka", "Tamil Nadu", "Goa"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the largest freshwater lake in India?", options: ["Dal Lake", "Chilika Lake", "Wular Lake", "Loktak Lake"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which Indian state has the most districts?", options: ["Madhya Pradesh", "Uttar Pradesh", "Maharashtra", "Rajasthan"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Rann of Kutch is located in which state?", options: ["Rajasthan", "Maharashtra", "Gujarat", "Madhya Pradesh"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the capital of Maharashtra?", options: ["Pune", "Nagpur", "Mumbai", "Nashik"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which city is known as the 'City of Lakes'?", options: ["Bhopal", "Udaipur", "Srinagar", "Nainital"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Kaziranga National Park is famous for which animal?", options: ["Tiger", "Elephant", "One-horned Rhinoceros", "Lion"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which river flows through New Delhi?", options: ["Ganga", "Yamuna", "Saraswati", "Chambal"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the highest plateau in India?", options: ["Deccan Plateau", "Malwa Plateau", "Ladakh Plateau", "Chota Nagpur Plateau"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which city is called the 'Garden City of India'?", options: ["Mysore", "Bengaluru", "Chandigarh", "Pune"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Gir National Park is famous for which animal?", options: ["Tiger", "Asiatic Lion", "Leopard", "Elephant"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which state is the largest producer of rice in India?", options: ["Punjab", "West Bengal", "Uttar Pradesh", "Andhra Pradesh"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which ocean lies to the south of India?", options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the capital of Uttarakhand?", options: ["Haridwar", "Dehradun", "Nainital", "Rishikesh"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Wular Lake is located in which state?", options: ["Himachal Pradesh", "Jammu & Kashmir", "Uttarakhand", "Sikkim"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which pass connects Srinagar with Leh?", options: ["Rohtang Pass", "Zoji La", "Khyber Pass", "Nathu La"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the capital of Assam?", options: ["Guwahati", "Dispur", "Shillong", "Imphal"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Nainital is located in which state?", options: ["Himachal Pradesh", "Uttarakhand", "Sikkim", "Jammu & Kashmir"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which state is known as the 'Spice Garden of India'?", options: ["Tamil Nadu", "Karnataka", "Kerala", "Andhra Pradesh"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the capital of Sikkim?", options: ["Darjeeling", "Gangtok", "Kalimpong", "Namchi"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which city is known as the 'Pearl City'?", options: ["Surat", "Hyderabad", "Jaipur", "Kochi"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which is the largest island of India?", options: ["Lakshadweep", "Middle Andaman", "Majuli", "Sriharikota"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Panna National Park is famous for which animal?", options: ["Elephant", "Tiger", "Rhino", "Deer"], correctAnswer: 1, difficulty: "easy", category: "India GK" },

  // ═══════════════════════════════════════════════════════════════
  //  INDIA — History & Freedom Struggle (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "Who is known as the 'Father of the Nation' in India?", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "Sardar Patel"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "India gained independence in which year?", options: ["1945", "1946", "1947", "1950"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who was the first Prime Minister of India?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Rajendra Prasad", "Sardar Patel"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who was the first President of India?", options: ["Jawaharlal Nehru", "Sardar Patel", "Rajendra Prasad", "S. Radhakrishnan"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Jallianwala Bagh massacre took place in which year?", options: ["1917", "1919", "1920", "1921"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who gave the slogan 'Do or Die'?", options: ["Subhas Chandra Bose", "Bhagat Singh", "Mahatma Gandhi", "Bal Gangadhar Tilak"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Quit India Movement was launched in which year?", options: ["1940", "1942", "1944", "1946"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who founded the Indian National Congress?", options: ["Mahatma Gandhi", "A.O. Hume", "Dadabhai Naoroji", "Gopal Krishna Gokhale"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Battle of Plassey was fought in which year?", options: ["1757", "1764", "1857", "1761"], correctAnswer: 0, difficulty: "easy", category: "Indian History" },
  { question: "Who is known as the 'Iron Man of India'?", options: ["Jawaharlal Nehru", "Bhagat Singh", "Sardar Vallabhbhai Patel", "Subhas Chandra Bose"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who built the Taj Mahal?", options: ["Akbar", "Shah Jahan", "Jahangir", "Aurangzeb"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Indian Constitution was adopted on which date?", options: ["15 August 1947", "26 January 1950", "26 November 1949", "30 January 1948"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Republic Day is celebrated on which date?", options: ["15 August", "26 January", "2 October", "14 November"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who gave the slogan 'Jai Hind'?", options: ["Mahatma Gandhi", "Bhagat Singh", "Subhas Chandra Bose", "Lala Lajpat Rai"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The first war of Indian independence was fought in which year?", options: ["1757", "1857", "1885", "1919"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who was the last Mughal Emperor?", options: ["Akbar", "Aurangzeb", "Bahadur Shah Zafar", "Shah Jahan"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Chandragupta Maurya was the founder of which dynasty?", options: ["Gupta Dynasty", "Maurya Dynasty", "Mughal Dynasty", "Chola Dynasty"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who wrote the Indian national anthem 'Jana Gana Mana'?", options: ["Bankim Chandra Chattopadhyay", "Rabindranath Tagore", "Sarojini Naidu", "Mahatma Gandhi"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who wrote 'Vande Mataram'?", options: ["Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Iqbal", "Premchand"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Dandi March was associated with which movement?", options: ["Quit India", "Non-Cooperation", "Civil Disobedience", "Swadeshi"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who is known as the 'Nightingale of India'?", options: ["Lata Mangeshkar", "Sarojini Naidu", "Indira Gandhi", "Mother Teresa"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Ashoka the Great belonged to which dynasty?", options: ["Gupta", "Maurya", "Mughal", "Chola"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who gave the slogan 'Tum Mujhe Khoon Do, Main Tumhe Azadi Dunga'?", options: ["Bhagat Singh", "Mahatma Gandhi", "Subhas Chandra Bose", "Chandrashekhar Azad"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Red Fort is located in which city?", options: ["Agra", "Jaipur", "New Delhi", "Lucknow"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who was known as 'Chacha Nehru'?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Rajendra Prasad", "Lal Bahadur Shastri"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Which Mughal Emperor built Fatehpur Sikri?", options: ["Shah Jahan", "Humayun", "Akbar", "Babur"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Bhagat Singh was executed in which year?", options: ["1929", "1930", "1931", "1932"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who was the first woman Prime Minister of India?", options: ["Sarojini Naidu", "Indira Gandhi", "Pratibha Patil", "Sonia Gandhi"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Simon Commission came to India in which year?", options: ["1927", "1928", "1929", "1930"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who is called the 'Grand Old Man of India'?", options: ["Mahatma Gandhi", "Dadabhai Naoroji", "Gopal Krishna Gokhale", "Bal Gangadhar Tilak"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who gave the slogan 'Swaraj is my birthright'?", options: ["Mahatma Gandhi", "Bal Gangadhar Tilak", "Bhagat Singh", "Lala Lajpat Rai"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Khilafat Movement was started in which year?", options: ["1919", "1920", "1921", "1922"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who was the founder of the Sikh Empire?", options: ["Guru Nanak", "Guru Gobind Singh", "Ranjit Singh", "Banda Bahadur"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Konark Sun Temple is located in which state?", options: ["Madhya Pradesh", "Odisha", "Rajasthan", "Tamil Nadu"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who was the first Indian woman to win a Nobel Prize?", options: ["Sarojini Naidu", "Mother Teresa", "Indira Gandhi", "Kiran Bedi"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "The Rowlatt Act was passed in which year?", options: ["1917", "1918", "1919", "1920"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who established the Arya Samaj?", options: ["Raja Ram Mohan Roy", "Swami Vivekananda", "Swami Dayanand Saraswati", "Ishwar Chandra Vidyasagar"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Lucknow Pact was signed in which year?", options: ["1914", "1915", "1916", "1917"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "Who founded the Brahmo Samaj?", options: ["Swami Vivekananda", "Raja Ram Mohan Roy", "Dayanand Saraswati", "Ramakrishna"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Gandhi ji started the Non-Cooperation Movement in which year?", options: ["1919", "1920", "1921", "1922"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Which city was the capital of India before Delhi?", options: ["Mumbai", "Kolkata", "Chennai", "Lucknow"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who designed the Indian Parliament building?", options: ["Charles Correa", "Edwin Lutyens", "Herbert Baker", "Le Corbusier"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Indian flag was designed by whom?", options: ["Mahatma Gandhi", "Pingali Venkayya", "Jawaharlal Nehru", "B.R. Ambedkar"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who is known as the 'Father of the Indian Constitution'?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "B.R. Ambedkar", "Sardar Patel"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Swadeshi Movement started in which year?", options: ["1903", "1905", "1907", "1909"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Who was the last Governor-General of free India?", options: ["Lord Mountbatten", "C. Rajagopalachari", "Warren Hastings", "Lord Curzon"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },
  { question: "Hawa Mahal is located in which city?", options: ["Jodhpur", "Udaipur", "Jaipur", "Bikaner"], correctAnswer: 2, difficulty: "easy", category: "Indian History" },
  { question: "The Gateway of India is located in which city?", options: ["New Delhi", "Chennai", "Kolkata", "Mumbai"], correctAnswer: 3, difficulty: "easy", category: "Indian History" },
  { question: "Qutub Minar is located in which city?", options: ["Agra", "Delhi", "Jaipur", "Lucknow"], correctAnswer: 1, difficulty: "easy", category: "Indian History" },

  // ═══════════════════════════════════════════════════════════════
  //  INDIA — National Symbols & Polity (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "What is the national animal of India?", options: ["Lion", "Elephant", "Tiger", "Leopard"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "What is the national bird of India?", options: ["Parrot", "Sparrow", "Peacock", "Eagle"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "What is the national flower of India?", options: ["Rose", "Sunflower", "Jasmine", "Lotus"], correctAnswer: 3, difficulty: "easy", category: "India GK" },
  { question: "What is the national fruit of India?", options: ["Apple", "Banana", "Mango", "Guava"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "What is the national sport of India?", options: ["Cricket", "Hockey", "Kabaddi", "Badminton"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "How many spokes are there in the Ashoka Chakra?", options: ["22", "24", "26", "28"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "What is the national tree of India?", options: ["Neem", "Peepal", "Banyan", "Mango"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "What is the national game of India (traditional)?", options: ["Cricket", "Hockey", "Kabaddi", "Football"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "The Indian national flag has how many colours?", options: ["2", "3", "4", "5"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "What is the currency of India?", options: ["Dollar", "Rupee", "Pound", "Yen"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "How many Union Territories are there in India?", options: ["6", "7", "8", "9"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the highest civilian award in India?", options: ["Padma Shri", "Padma Bhushan", "Padma Vibhushan", "Bharat Ratna"], correctAnswer: 3, difficulty: "easy", category: "India GK" },
  { question: "The Rajya Sabha is also known as?", options: ["House of People", "Council of States", "Parliament House", "Legislative Assembly"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "The Lok Sabha is also known as?", options: ["Council of States", "House of People", "Senate", "Assembly"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Who is the Supreme Commander of the Indian Armed Forces?", options: ["Prime Minister", "Defence Minister", "Army Chief", "President"], correctAnswer: 3, difficulty: "easy", category: "India GK" },
  { question: "Which article of the Indian Constitution abolishes untouchability?", options: ["Article 14", "Article 15", "Article 17", "Article 21"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The Right to Education is a which type of right?", options: ["Legal Right", "Fundamental Right", "Directive Principle", "Statutory Right"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Who appoints the Chief Justice of India?", options: ["Prime Minister", "Parliament", "President", "Law Minister"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "India is a ___ country.", options: ["Monarchy", "Dictatorship", "Democratic Republic", "Communist"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The Preamble of India begins with which words?", options: ["We the Citizens", "We the People", "We the Nation", "We the Republic"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Who was the first Chief Justice of India?", options: ["H.J. Kania", "M. Patanjali Sastri", "B.K. Mukherjea", "S.R. Das"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "The minimum age to become the President of India is?", options: ["25 years", "30 years", "35 years", "40 years"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The Indian Parliament consists of how many houses?", options: ["1", "2", "3", "4"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Which language has the most native speakers in India?", options: ["English", "Bengali", "Hindi", "Tamil"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "ISRO stands for?", options: ["Indian Space Research Organisation", "Indian Science Research Organisation", "International Space Research Organisation", "Indian Space Rocket Organisation"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "RBI stands for?", options: ["Reserve Bank of India", "Regional Bank of India", "Royal Bank of India", "Rural Bank of India"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "The Reserve Bank of India was established in which year?", options: ["1930", "1935", "1940", "1947"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Indian Standard Time is ahead of Greenwich Mean Time by?", options: ["4 hours 30 min", "5 hours", "5 hours 30 min", "6 hours"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "IIT stands for?", options: ["Indian Institute of Technology", "International Institute of Technology", "Indian Institute of Training", "Indian Institute of Telecommunication"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Who was the first Indian to go to space?", options: ["Kalpana Chawla", "Sunita Williams", "Rakesh Sharma", "A.P.J. Abdul Kalam"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "India's first satellite was named?", options: ["Bhaskara", "Rohini", "Aryabhata", "INSAT"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Which is the largest bank of India?", options: ["PNB", "HDFC", "SBI", "ICICI"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "PIN code has how many digits?", options: ["4", "5", "6", "7"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The national anthem of India takes approximately how many seconds to sing?", options: ["42 seconds", "52 seconds", "62 seconds", "72 seconds"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "India is in which continent?", options: ["Africa", "Europe", "Asia", "South America"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The saffron color in the Indian flag represents?", options: ["Peace", "Courage and sacrifice", "Fertility", "Truth"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "How many languages are listed in the Eighth Schedule of the Constitution?", options: ["14", "18", "22", "24"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Gandhi Jayanti is celebrated on which date?", options: ["15 August", "26 January", "2 October", "14 November"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Children's Day is celebrated on which date in India?", options: ["5 September", "14 November", "1 June", "20 November"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Teachers' Day is celebrated on which date?", options: ["5 September", "14 November", "15 August", "2 October"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Which Indian state was formed first after independence?", options: ["Gujarat", "Kerala", "Andhra Pradesh", "Karnataka"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "What does the green colour in the Indian flag represent?", options: ["Courage", "Peace", "Fertility and growth", "Truth"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "Who is called the 'Missile Man of India'?", options: ["Vikram Sarabhai", "Homi Bhabha", "A.P.J. Abdul Kalam", "C.V. Raman"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The national emblem of India has how many lions visible?", options: ["2", "3", "4", "1"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "What is India's rank by population in the world?", options: ["1st", "2nd", "3rd", "4th"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Which is the official language of the Indian government?", options: ["English", "Hindi", "Hindi and English", "Sanskrit"], correctAnswer: 2, difficulty: "easy", category: "India GK" },
  { question: "The motto of India 'Satyameva Jayate' means?", options: ["Truth Alone Triumphs", "Unity in Diversity", "One Nation One People", "Victory to India"], correctAnswer: 0, difficulty: "easy", category: "India GK" },
  { question: "Who was the first woman President of India?", options: ["Indira Gandhi", "Pratibha Patil", "Sarojini Naidu", "Sonia Gandhi"], correctAnswer: 1, difficulty: "easy", category: "India GK" },
  { question: "Independence Day of India is celebrated on?", options: ["26 January", "15 August", "2 October", "14 November"], correctAnswer: 1, difficulty: "easy", category: "India GK" },

  // ═══════════════════════════════════════════════════════════════
  //  WORLD — Geography (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "Which is the largest country in the world by area?", options: ["Canada", "China", "USA", "Russia"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "Which is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which is the largest ocean in the world?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "Which is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which is the largest desert in the world?", options: ["Gobi", "Kalahari", "Sahara", "Arabian"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which is the highest mountain in the world?", options: ["K2", "Kangchenjunga", "Mount Everest", "Makalu"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "How many continents are there in the world?", options: ["5", "6", "7", "8"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which continent is known as the 'Dark Continent'?", options: ["Asia", "South America", "Africa", "Australia"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which is the largest continent?", options: ["Africa", "North America", "Europe", "Asia"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "Which is the smallest continent?", options: ["Europe", "Australia", "Antarctica", "South America"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of France?", options: ["Lyon", "Marseille", "Nice", "Paris"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of the United States?", options: ["New York", "Los Angeles", "Washington D.C.", "Chicago"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of China?", options: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which country is called the 'Land of the Rising Sun'?", options: ["China", "Thailand", "Japan", "South Korea"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which is the largest lake in the world?", options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "The Great Wall is located in which country?", options: ["Japan", "India", "China", "Mongolia"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which country has the most population in the world?", options: ["USA", "China", "India", "Indonesia"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Victoria Falls is located between which two countries?", options: ["Kenya & Tanzania", "Zambia & Zimbabwe", "South Africa & Namibia", "Congo & Cameroon"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which is the deepest ocean in the world?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "The Amazon Rainforest is in which continent?", options: ["Africa", "Asia", "South America", "North America"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Germany?", options: ["Munich", "Hamburg", "Frankfurt", "Berlin"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "Which is the largest island in the world?", options: ["Madagascar", "Borneo", "Greenland", "New Guinea"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Niagara Falls is on the border of which two countries?", options: ["USA & Mexico", "USA & Canada", "Canada & Greenland", "USA & Brazil"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Russia?", options: ["St. Petersburg", "Moscow", "Vladivostok", "Novosibirsk"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Italy?", options: ["Milan", "Venice", "Rome", "Florence"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which country is known as the 'Land of Kangaroos'?", options: ["New Zealand", "South Africa", "Australia", "Argentina"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Egypt?", options: ["Alexandria", "Cairo", "Luxor", "Aswan"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "The Statue of Liberty is located in which country?", options: ["France", "UK", "USA", "Canada"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which is the hottest continent?", options: ["Asia", "South America", "Africa", "Australia"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which ocean separates Europe from America?", options: ["Pacific", "Indian", "Atlantic", "Arctic"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "The Pyramids are located in which country?", options: ["Sudan", "Libya", "Egypt", "Morocco"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of the United Kingdom?", options: ["Edinburgh", "Manchester", "London", "Birmingham"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which country is known as the 'Land of Windmills'?", options: ["Denmark", "Netherlands", "Belgium", "Sweden"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Seville", "Valencia"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which country is the largest producer of coffee?", options: ["Colombia", "Vietnam", "Brazil", "Ethiopia"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which strait separates Asia from North America?", options: ["Strait of Hormuz", "Bering Strait", "Strait of Malacca", "Strait of Gibraltar"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "The Eiffel Tower is located in which city?", options: ["London", "Rome", "Berlin", "Paris"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "The Colosseum is located in which city?", options: ["Athens", "Rome", "Paris", "Istanbul"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Pakistan?", options: ["Karachi", "Lahore", "Islamabad", "Rawalpindi"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "Which is the longest wall in the world?", options: ["Berlin Wall", "Hadrian's Wall", "Great Wall of China", "Western Wall"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of South Korea?", options: ["Busan", "Incheon", "Seoul", "Daegu"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Sri Lanka?", options: ["Colombo", "Kandy", "Galle", "Sri Jayawardenepura Kotte"], correctAnswer: 3, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Nepal?", options: ["Pokhara", "Kathmandu", "Biratnagar", "Lalitpur"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Bangladesh?", options: ["Chittagong", "Dhaka", "Sylhet", "Rajshahi"], correctAnswer: 1, difficulty: "easy", category: "World GK" },
  { question: "Which country is called the 'Land of Thunder Dragon'?", options: ["Nepal", "Myanmar", "Bhutan", "Tibet"], correctAnswer: 2, difficulty: "easy", category: "World GK" },
  { question: "What is the capital of Thailand?", options: ["Chiang Mai", "Phuket", "Bangkok", "Pattaya"], correctAnswer: 2, difficulty: "easy", category: "World GK" },

  // ═══════════════════════════════════════════════════════════════
  //  WORLD — History & Leaders (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "Who discovered America?", options: ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Marco Polo"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "World War II ended in which year?", options: ["1943", "1944", "1945", "1946"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "World War I started in which year?", options: ["1912", "1914", "1916", "1918"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who was the first President of the United States?", options: ["Abraham Lincoln", "Thomas Jefferson", "George Washington", "John Adams"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The French Revolution started in which year?", options: ["1776", "1789", "1799", "1804"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who invented the telephone?", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who invented the light bulb?", options: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Benjamin Franklin"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Pablo Picasso"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The Berlin Wall fell in which year?", options: ["1987", "1988", "1989", "1990"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was the leader of Nazi Germany?", options: ["Mussolini", "Stalin", "Hitler", "Churchill"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Nelson Mandela was the President of which country?", options: ["Nigeria", "Kenya", "South Africa", "Ghana"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was the first man to walk on the moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The United Nations was founded in which year?", options: ["1942", "1945", "1948", "1950"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who was the first woman to fly solo across the Atlantic?", options: ["Amelia Earhart", "Valentina Tereshkova", "Harriet Quimby", "Bessie Coleman"], correctAnswer: 0, difficulty: "easy", category: "World History" },
  { question: "The Olympic Games originated in which country?", options: ["Italy", "France", "Greece", "Egypt"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who discovered gravity?", options: ["Albert Einstein", "Isaac Newton", "Galileo", "Archimedes"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who developed the theory of relativity?", options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Stephen Hawking"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was the first person to fly in space?", options: ["Neil Armstrong", "Alan Shepard", "Yuri Gagarin", "John Glenn"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The American Civil War started in which year?", options: ["1855", "1861", "1865", "1870"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who invented the printing press?", options: ["Thomas Edison", "Johannes Gutenberg", "Benjamin Franklin", "Galileo"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The Renaissance started in which country?", options: ["France", "England", "Germany", "Italy"], correctAnswer: 3, difficulty: "easy", category: "World History" },
  { question: "Who was known as the 'Iron Lady'?", options: ["Indira Gandhi", "Margaret Thatcher", "Angela Merkel", "Golda Meir"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The Cold War was between which two superpowers?", options: ["USA & China", "USA & USSR", "UK & Germany", "France & Russia"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who founded Microsoft?", options: ["Steve Jobs", "Mark Zuckerberg", "Bill Gates", "Jeff Bezos"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who founded Apple?", options: ["Bill Gates", "Elon Musk", "Steve Jobs", "Larry Page"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who is known as the father of computers?", options: ["Alan Turing", "Charles Babbage", "John von Neumann", "Bill Gates"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The Industrial Revolution started in which country?", options: ["France", "Germany", "USA", "England"], correctAnswer: 3, difficulty: "easy", category: "World History" },
  { question: "Who was the Queen of Egypt known for her beauty?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Martin Luther King Jr. was a leader of which movement?", options: ["Women's Rights", "Civil Rights", "Labor Rights", "Anti-War"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who wrote 'A Brief History of Time'?", options: ["Albert Einstein", "Isaac Newton", "Stephen Hawking", "Richard Feynman"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The Nobel Prize was established by whom?", options: ["Albert Einstein", "Alfred Nobel", "Marie Curie", "Isaac Newton"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The first nuclear bomb was dropped on which city?", options: ["Nagasaki", "Tokyo", "Hiroshima", "Osaka"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was the first woman to win a Nobel Prize?", options: ["Mother Teresa", "Marie Curie", "Dorothy Hodgkin", "Rosalind Franklin"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "The Titanic sank in which year?", options: ["1910", "1911", "1912", "1913"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who invented the World Wide Web?", options: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who was the first female Prime Minister in the world?", options: ["Margaret Thatcher", "Golda Meir", "Indira Gandhi", "Sirimavo Bandaranaike"], correctAnswer: 3, difficulty: "easy", category: "World History" },
  { question: "The Great Depression started in which year?", options: ["1925", "1929", "1932", "1935"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who wrote 'The Origin of Species'?", options: ["Isaac Newton", "Albert Einstein", "Charles Darwin", "Gregor Mendel"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The Panama Canal connects which two oceans?", options: ["Atlantic & Indian", "Pacific & Indian", "Atlantic & Pacific", "Arctic & Atlantic"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was the first Black President of the United States?", options: ["Martin Luther King Jr.", "Colin Powell", "Barack Obama", "Condoleezza Rice"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who founded Facebook?", options: ["Bill Gates", "Elon Musk", "Steve Jobs", "Mark Zuckerberg"], correctAnswer: 3, difficulty: "easy", category: "World History" },
  { question: "The Leaning Tower of Pisa is in which country?", options: ["France", "Spain", "Italy", "Greece"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The Suez Canal is in which country?", options: ["India", "Egypt", "Turkey", "Iran"], correctAnswer: 1, difficulty: "easy", category: "World History" },
  { question: "Who invented the airplane?", options: ["Thomas Edison", "Henry Ford", "Wright Brothers", "Alexander Graham Bell"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who invented the steam engine?", options: ["James Watt", "Thomas Edison", "Nikola Tesla", "Isaac Newton"], correctAnswer: 0, difficulty: "easy", category: "World History" },
  { question: "Who was the first emperor of China?", options: ["Sun Tzu", "Confucius", "Qin Shi Huang", "Genghis Khan"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "The Roman Empire was centered in which modern-day country?", options: ["Greece", "Spain", "Italy", "France"], correctAnswer: 2, difficulty: "easy", category: "World History" },
  { question: "Who was Alexander the Great from?", options: ["Rome", "Egypt", "Persia", "Macedonia (Greece)"], correctAnswer: 3, difficulty: "easy", category: "World History" },
  { question: "Who invented penicillin?", options: ["Louis Pasteur", "Alexander Fleming", "Robert Koch", "Edward Jenner"], correctAnswer: 1, difficulty: "easy", category: "World History" },

  // ═══════════════════════════════════════════════════════════════
  //  SCIENCE — Easy (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "How many bones does an adult human body have?", options: ["186", "196", "206", "216"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the chemical formula of water?", options: ["CO2", "H2O", "NaCl", "O2"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which is the largest organ of the human body?", options: ["Heart", "Liver", "Brain", "Skin"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "What is the boiling point of water?", options: ["90°C", "100°C", "110°C", "120°C"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "How many teeth does a normal adult human have?", options: ["28", "30", "32", "34"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which blood type is known as the universal donor?", options: ["A", "B", "AB", "O"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "The Earth revolves around the Sun in how many days?", options: ["360", "365", "370", "355"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "What is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which gas is most abundant in the Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "Speed of light is approximately?", options: ["3 × 10⁶ m/s", "3 × 10⁷ m/s", "3 × 10⁸ m/s", "3 × 10⁹ m/s"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which vitamin is produced by sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "Which is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "What is the chemical symbol for Gold?", options: ["Go", "Gd", "Au", "Ag"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the chemical symbol for Iron?", options: ["Ir", "Fe", "In", "Io"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which part of the plant conducts photosynthesis?", options: ["Root", "Stem", "Leaf", "Flower"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Body"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "The study of stars and planets is called?", options: ["Astrology", "Astronomy", "Geology", "Meteorology"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which metal is liquid at room temperature?", options: ["Lead", "Zinc", "Mercury", "Aluminium"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the freezing point of water?", options: ["-10°C", "0°C", "10°C", "4°C"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Sound cannot travel through what?", options: ["Water", "Air", "Vacuum", "Metal"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dinitrogen Acid", "Deoxyribose Nucleic Atom", "Dynamic Natural Acid"], correctAnswer: 0, difficulty: "easy", category: "Science" },
  { question: "Which is the nearest star to the Earth?", options: ["Sirius", "Alpha Centauri", "Sun", "Polaris"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the pH of pure water?", options: ["5", "6", "7", "8"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which organ pumps blood in the body?", options: ["Lungs", "Brain", "Liver", "Heart"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "What causes a rainbow?", options: ["Wind", "Rain only", "Refraction of sunlight", "Clouds"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which gas do we breathe in?", options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Humans have how many chromosomes?", options: ["44", "46", "48", "42"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "What does CO2 stand for?", options: ["Carbon Monoxide", "Carbon Dioxide", "Calcium Oxide", "Cobalt Oxide"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which is the smallest bone in the human body?", options: ["Femur", "Stapes", "Radius", "Tibia"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which is the largest bone in the human body?", options: ["Humerus", "Tibia", "Femur", "Spine"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What does the study of Zoology deal with?", options: ["Plants", "Rocks", "Animals", "Weather"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What does the study of Botany deal with?", options: ["Animals", "Earth", "Stars", "Plants"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "The Moon revolves around what?", options: ["Sun", "Earth", "Mars", "Venus"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "An atom is made up of protons, neutrons and?", options: ["Photons", "Electrons", "Quarks", "Ions"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "Which force keeps us on the ground?", options: ["Friction", "Magnetism", "Gravity", "Inertia"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "High Tech Transfer Protocol", "HyperText Transmission Page", "Home Tool Transfer Protocol"], correctAnswer: 0, difficulty: "easy", category: "Science" },
  { question: "What is the unit of electrical resistance?", options: ["Ampere", "Volt", "Watt", "Ohm"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "1 kilometre equals how many metres?", options: ["100", "500", "1000", "10000"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "The Sun is a?", options: ["Planet", "Moon", "Star", "Comet"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "NaCl is the chemical formula for?", options: ["Sugar", "Water", "Salt", "Baking Soda"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What is the SI unit of force?", options: ["Joule", "Watt", "Pascal", "Newton"], correctAnswer: 3, difficulty: "easy", category: "Science" },
  { question: "What colour is chlorophyll?", options: ["Red", "Blue", "Green", "Yellow"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "What is the filament in a light bulb made of?", options: ["Copper", "Aluminum", "Tungsten", "Iron"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "Which instrument is used to measure temperature?", options: ["Barometer", "Thermometer", "Hygrometer", "Speedometer"], correctAnswer: 1, difficulty: "easy", category: "Science" },
  { question: "How many colours are in a rainbow?", options: ["5", "6", "7", "8"], correctAnswer: 2, difficulty: "easy", category: "Science" },
  { question: "What percentage of the Earth's surface is covered by water?", options: ["51%", "61%", "71%", "81%"], correctAnswer: 2, difficulty: "easy", category: "Science" },

  // ═══════════════════════════════════════════════════════════════
  //  SPORTS (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "How many players are on a cricket team?", options: ["9", "10", "11", "12"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "How many players are on a football (soccer) team?", options: ["9", "10", "11", "12"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Which country won the first Cricket World Cup in 1975?", options: ["Australia", "India", "England", "West Indies"], correctAnswer: 3, difficulty: "easy", category: "Sports" },
  { question: "The Olympic Games are held every how many years?", options: ["2", "3", "4", "5"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which sport is the term 'LBW' used?", options: ["Football", "Tennis", "Cricket", "Hockey"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Who is known as the 'God of Cricket'?", options: ["Virat Kohli", "MS Dhoni", "Sachin Tendulkar", "Kapil Dev"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "FIFA is associated with which sport?", options: ["Cricket", "Football", "Tennis", "Hockey"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "How many players are in a basketball team (on court)?", options: ["4", "5", "6", "7"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "In which sport is the term 'serve' used?", options: ["Football", "Cricket", "Tennis", "Hockey"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The Wimbledon is associated with which sport?", options: ["Football", "Cricket", "Golf", "Tennis"], correctAnswer: 3, difficulty: "easy", category: "Sports" },
  { question: "Usain Bolt is famous for which sport?", options: ["Swimming", "Running (Sprint)", "Boxing", "Football"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "How many overs are there in a T20 cricket match (per team)?", options: ["10", "15", "20", "50"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In football, a 'hat-trick' means how many goals?", options: ["2", "3", "4", "5"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Who has scored the most runs in international cricket?", options: ["Ricky Ponting", "Virat Kohli", "Sachin Tendulkar", "Kumar Sangakkara"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which sport is the term 'ace' used?", options: ["Cricket", "Football", "Tennis", "Badminton"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The 2024 Summer Olympics were held in which city?", options: ["London", "Tokyo", "Paris", "Los Angeles"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The Hockey World Cup is associated with which sport?", options: ["Ice Hockey only", "Field Hockey", "Street Hockey", "Air Hockey"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In cricket, a century means scoring how many runs?", options: ["50", "100", "150", "200"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Who is considered the greatest footballer of all time (by most)?", options: ["Cristiano Ronaldo", "Pelé", "Lionel Messi", "Diego Maradona"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "In which sport do you use a shuttlecock?", options: ["Tennis", "Squash", "Badminton", "Table Tennis"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "India won the Cricket World Cup in 2011 under whose captaincy?", options: ["Virat Kohli", "Sourav Ganguly", "MS Dhoni", "Sachin Tendulkar"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "How many overs are in a One Day International (ODI) match per team?", options: ["20", "40", "50", "60"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Which sport is played at Wimbledon?", options: ["Golf", "Tennis", "Cricket", "Football"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Virat Kohli plays which sport?", options: ["Football", "Tennis", "Cricket", "Badminton"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "PV Sindhu is associated with which sport?", options: ["Tennis", "Badminton", "Table Tennis", "Archery"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Neeraj Chopra won an Olympic gold medal in which event?", options: ["Shot Put", "Discus Throw", "Javelin Throw", "Hammer Throw"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Mary Kom is associated with which sport?", options: ["Wrestling", "Boxing", "Judo", "Taekwondo"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "How many sets does a standard tennis match have (Men's Grand Slam)?", options: ["3", "4", "5", "6"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which sport is the term 'goal' most commonly used?", options: ["Cricket", "Tennis", "Football", "Badminton"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The IPL is a league for which sport?", options: ["Football", "Hockey", "Kabaddi", "Cricket"], correctAnswer: 3, difficulty: "easy", category: "Sports" },
  { question: "Roger Federer is associated with which sport?", options: ["Golf", "Badminton", "Tennis", "Table Tennis"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Which country is known as the birthplace of cricket?", options: ["India", "Australia", "England", "South Africa"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "How many players are on a volleyball team (on court)?", options: ["5", "6", "7", "8"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "The term 'checkmate' is used in which game?", options: ["Cards", "Ludo", "Chess", "Carrom"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which sport is the term 'strike' used?", options: ["Cricket", "Bowling", "Tennis", "Golf"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Which Indian cricketer is known as 'Captain Cool'?", options: ["Virat Kohli", "Rohit Sharma", "MS Dhoni", "Sourav Ganguly"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In football, a red card means what?", options: ["Warning", "Free kick", "Sent off", "Goal"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Which country invented table tennis?", options: ["China", "Japan", "England", "France"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "How many gold medals did Michael Phelps win in his career?", options: ["18", "21", "23", "25"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The Ashes is a cricket series between which two countries?", options: ["India & Pakistan", "Australia & England", "India & Australia", "England & South Africa"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Milkha Singh was known as?", options: ["Flying Sikh", "Golden Boy", "Sprint King", "Lightning Singh"], correctAnswer: 0, difficulty: "easy", category: "Sports" },
  { question: "In cricket, what is the maximum score a batsman can hit off one ball?", options: ["4", "6", "8", "12"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "The Rugby World Cup trophy is called?", options: ["Jules Rimet", "Webb Ellis Cup", "Stanley Cup", "Ashes Urn"], correctAnswer: 1, difficulty: "easy", category: "Sports" },
  { question: "Which Indian state is famous for boat racing?", options: ["Tamil Nadu", "West Bengal", "Kerala", "Goa"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which year did India first win the Cricket World Cup?", options: ["1975", "1979", "1983", "1987"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "The term 'birdie' is used in which sport?", options: ["Tennis", "Badminton", "Golf", "Cricket"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Who holds the record for the fastest century in ODI cricket?", options: ["Virender Sehwag", "Chris Gayle", "AB de Villiers", "Shahid Afridi"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "Which game uses the term 'love' for zero?", options: ["Cricket", "Football", "Tennis", "Badminton"], correctAnswer: 2, difficulty: "easy", category: "Sports" },
  { question: "In which sport can you score a 'try'?", options: ["Football", "Cricket", "Rugby", "Basketball"], correctAnswer: 2, difficulty: "easy", category: "Sports" },

  // ═══════════════════════════════════════════════════════════════
  //  ENTERTAINMENT & CULTURE (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "Bollywood is the film industry of which country?", options: ["Pakistan", "Bangladesh", "India", "Sri Lanka"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Hollywood is located in which city?", options: ["New York", "Chicago", "Los Angeles", "San Francisco"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the most spoken language in the world?", options: ["Hindi", "English", "Spanish", "Mandarin Chinese"], correctAnswer: 3, difficulty: "easy", category: "General Knowledge" },
  { question: "How many days are there in a leap year?", options: ["364", "365", "366", "367"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many days are there in a normal year?", options: ["364", "365", "366", "360"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "How many months have 31 days?", options: ["5", "6", "7", "8"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the largest mammal in the world?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the fastest land animal?", options: ["Lion", "Horse", "Cheetah", "Deer"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the tallest animal in the world?", options: ["Elephant", "Camel", "Giraffe", "Ostrich"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which bird is the largest in the world?", options: ["Eagle", "Penguin", "Ostrich", "Albatross"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "A group of lions is called?", options: ["Pack", "Herd", "Pride", "Flock"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Baby of a dog is called?", options: ["Cub", "Kitten", "Puppy", "Calf"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many sides does a triangle have?", options: ["2", "3", "4", "5"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "How many sides does a hexagon have?", options: ["4", "5", "6", "8"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the Roman numeral for 10?", options: ["V", "X", "L", "D"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the Roman numeral for 100?", options: ["C", "D", "L", "M"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the most widely used search engine?", options: ["Yahoo", "Bing", "Google", "DuckDuckGo"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "WhatsApp was founded by whom?", options: ["Mark Zuckerberg", "Jan Koum", "Jack Dorsey", "Evan Spiegel"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Bitcoin was invented by?", options: ["Elon Musk", "Bill Gates", "Satoshi Nakamoto", "Vitalik Buterin"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What does GPS stand for?", options: ["General Positioning System", "Global Positioning System", "Geo Physical System", "Geographic Placement System"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What does Wi-Fi stand for?", options: ["Wireless Fidelity", "Wide Fiber", "Wireless Fiber", "Windows Fidelity"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "What does SIM stand for?", options: ["System Identity Module", "Subscriber Identity Module", "Signal Information Module", "Simple Identity Module"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What does ATM stand for?", options: ["Automatic Teller Machine", "Auto Transaction Machine", "Automated Transfer Machine", "All Time Money"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "What does USB stand for?", options: ["Universal Serial Bus", "United System Bus", "Unified Serial Bridge", "Universal System Board"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which company makes the iPhone?", options: ["Samsung", "Google", "Apple", "Microsoft"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which planet is known as the 'Morning Star'?", options: ["Mars", "Jupiter", "Venus", "Mercury"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is a baby cat called?", options: ["Puppy", "Cub", "Kitten", "Foal"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the largest bird egg?", options: ["Eagle", "Ostrich", "Emu", "Penguin"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which animal is known as the 'Ship of the Desert'?", options: ["Horse", "Donkey", "Camel", "Elephant"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the young one of a horse called?", options: ["Calf", "Lamb", "Foal", "Kid"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "8"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the square root of 144?", options: ["10", "11", "12", "14"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is 15 × 15?", options: ["200", "215", "225", "250"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many zeros are in a million?", options: ["5", "6", "7", "8"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "A leap year comes every how many years?", options: ["2", "3", "4", "5"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which festival is known as the 'Festival of Lights'?", options: ["Holi", "Eid", "Diwali", "Christmas"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Holi is known as the 'Festival of ___'?", options: ["Lights", "Colours", "Harvest", "Water"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Christmas is celebrated on which date?", options: ["24 December", "25 December", "31 December", "1 January"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the smallest prime number?", options: ["0", "1", "2", "3"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is half of 500?", options: ["200", "250", "300", "225"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },

  // ═══════════════════════════════════════════════════════════════
  //  ECONOMY & MISC (50)
  // ═══════════════════════════════════════════════════════════════
  { question: "GST stands for?", options: ["Goods and Services Tax", "General Sales Tax", "Government Service Tax", "Gross Sales Tax"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "GDP stands for?", options: ["General Domestic Product", "Gross Domestic Product", "Grand Development Plan", "Growth Domestic Price"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "WHO stands for?", options: ["World Health Organisation", "World Human Organisation", "Western Health Office", "World Hospital Organisation"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "UNESCO stands for?", options: ["United Nations Educational, Scientific and Cultural Organisation", "United Nations Environmental Science Council", "Union of Nations for Education, Science and Culture", "United National Economic and Social Committee"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "The Euro is the currency of which region?", options: ["Asia", "European Union", "Africa", "South America"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "The Dollar is the currency of which country?", options: ["United Kingdom", "Japan", "United States", "Canada"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The Yen is the currency of which country?", options: ["China", "South Korea", "Japan", "Thailand"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "UPI stands for?", options: ["Unified Payments Interface", "Universal Payment India", "United Payment Integration", "Unified Pay Interface"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which Indian company launched UPI?", options: ["RBI", "SBI", "NPCI", "Paytm"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The World Bank headquarters is in which city?", options: ["New York", "Geneva", "Washington D.C.", "London"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The headquarters of the United Nations is in which city?", options: ["Geneva", "London", "Paris", "New York"], correctAnswer: 3, difficulty: "easy", category: "General Knowledge" },
  { question: "Which planet has rings around it?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "A decade is how many years?", options: ["5", "10", "15", "20"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "A century is how many years?", options: ["10", "50", "100", "1000"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "A millennium is how many years?", options: ["100", "500", "1000", "10000"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the full form of NASA?", options: ["National Aeronautics and Space Administration", "North American Space Agency", "National Association of Space Astronauts", "New Age Space Administration"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which country gifted the Statue of Liberty to the USA?", options: ["England", "Italy", "France", "Germany"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The Great Barrier Reef is located in which country?", options: ["Brazil", "India", "Australia", "South Africa"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which blood group is the universal receiver?", options: ["A", "B", "O", "AB"], correctAnswer: 3, difficulty: "easy", category: "General Knowledge" },
  { question: "Machu Picchu is located in which country?", options: ["Mexico", "Brazil", "Peru", "Colombia"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The currency of the United Kingdom is?", options: ["Euro", "Dollar", "Pound Sterling", "Franc"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What does 'www' stand for?", options: ["World Wide Web", "Western World Web", "Worldwide Wireless Web", "World Web Wired"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which gas is used in fire extinguishers?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which instrument is used to measure blood pressure?", options: ["Thermometer", "Stethoscope", "Sphygmomanometer", "ECG Machine"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What does LED stand for?", options: ["Light Emitting Diode", "Light Energy Device", "Low Energy Display", "Laser Emitting Diode"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "How many weeks are in a year?", options: ["48", "50", "52", "54"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The Red Cross was founded by?", options: ["Florence Nightingale", "Henry Dunant", "Mother Teresa", "Albert Schweitzer"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the tallest building in the world (as of 2024)?", options: ["Shanghai Tower", "Burj Khalifa", "One World Trade Center", "Taipei 101"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which country is known for the Kangaroo?", options: ["India", "Brazil", "South Africa", "Australia"], correctAnswer: 3, difficulty: "easy", category: "General Knowledge" },
  { question: "What does PDF stand for?", options: ["Portable Document Format", "Print Document File", "Page Design Format", "Personal Data File"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "What does RAM stand for?", options: ["Read Access Memory", "Random Access Memory", "Rapid Action Memory", "Remote Area Memory"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "How many hours are in a day?", options: ["12", "20", "24", "48"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many minutes are in an hour?", options: ["30", "45", "60", "100"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many seconds are in a minute?", options: ["30", "60", "90", "100"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What is 20% of 500?", options: ["50", "75", "100", "150"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "How many grams are in a kilogram?", options: ["10", "100", "1000", "10000"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which animal is known as man's best friend?", options: ["Cat", "Horse", "Dog", "Parrot"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "Which insect produces honey?", options: ["Ant", "Butterfly", "Bee", "Wasp"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the capital of Myanmar?", options: ["Yangon", "Mandalay", "Naypyidaw", "Bago"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The first Indian to receive the Nobel Prize was?", options: ["C.V. Raman", "Rabindranath Tagore", "Mother Teresa", "Amartya Sen"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the full form of PAN card?", options: ["Permanent Account Number", "Public Account Number", "Personal Account Number", "Primary Access Number"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Aadhar card has how many digits?", options: ["10", "12", "14", "16"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Indian mobile numbers have how many digits?", options: ["8", "10", "11", "12"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which animal is the national animal of Australia?", options: ["Koala", "Kangaroo", "Platypus", "Emu"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
  { question: "Which is the world's largest democracy?", options: ["USA", "UK", "India", "Brazil"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "The Bermuda Triangle is located in which ocean?", options: ["Pacific", "Indian", "Arctic", "Atlantic"], correctAnswer: 3, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the full form of OTP?", options: ["One Time Password", "Online Transaction Payment", "Open Transfer Protocol", "Official Time Pass"], correctAnswer: 0, difficulty: "easy", category: "General Knowledge" },
  { question: "Which organ in the human body filters blood?", options: ["Heart", "Liver", "Kidney", "Lungs"], correctAnswer: 2, difficulty: "easy", category: "General Knowledge" },
  { question: "What is the national game of China?", options: ["Badminton", "Table Tennis", "Kung Fu", "Cricket"], correctAnswer: 1, difficulty: "easy", category: "General Knowledge" },
];

async function seed() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGODB_URI);
    console.log("✅ Connected to MongoDB!");

    console.log(`Inserting ${questions.length} questions...`);
    await Question.insertMany(questions);
    
    const totalCount = await Question.countDocuments();
    console.log(`✅ Successfully added ${questions.length} new questions!`);
    console.log(`📊 Total questions in database now: ${totalCount}`);
    
    process.exit(0);
  } catch (err) {
    console.error("❌ Error:", err.message);
    process.exit(1);
  }
}

seed();
